---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: knative-eventing-kafka-channel-post-install-job-role
  labels:
    kafka.eventing.knative.dev/release: devel
rules:
  - apiGroups:
      - "apiextensions.k8s.io"
    resources:
      - "customresourcedefinitions"
      - "customresourcedefinitions/status"
    verbs:
      - "get"
      - "list"
      - "update"
      - "patch"
      - "watch"
  - apiGroups:
      - "messaging.knative.dev"
    resources:
      - "kafkachannels"
      - "kafkachannels/finalizers"
      - "kafkachannels/status"
    verbs:
      - "get"
      - "list"
      - "create"
      - "update"
      - "patch"
      - "watch"
  - apiGroups:
      - ""
    resources:
      - "namespaces"
    verbs:
      - "get"
      - "list"
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: knative-eventing-kafka-channel-post-install-job
  namespace: knative-eventing
  labels:
    kafka.eventing.knative.dev/release: devel
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: knative-eventing-kafka-channel-post-install-job-role-binding
  labels:
    kafka.eventing.knative.dev/release: devel
subjects:
  - kind: ServiceAccount
    name: knative-eventing-kafka-channel-post-install-job
    namespace: knative-eventing
roleRef:
  kind: ClusterRole
  name: knative-eventing-kafka-channel-post-install-job-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: batch/v1
kind: Job
metadata:
  generateName: storage-version-migration-eventing-kafka-channel-
  namespace: knative-eventing
  labels:
    app: "storage-version-migration-eventing-kafka-channel"
    kafka.eventing.knative.dev/release: devel
spec:
  ttlSecondsAfterFinished: 600
  backoffLimit: 10
  template:
    metadata:
      labels:
        app: "storage-version-migration-eventing-kafka-channel"
        kafka.eventing.knative.dev/release: devel
      annotations:
        sidecar.istio.io/inject: "false"
    spec:
      serviceAccountName: knative-eventing-kafka-channel-post-install-job
      restartPolicy: OnFailure
      containers:
        - name: migrate
          image: registry.ci.openshift.org/openshift/knative-v1.1.0:knative-eventing-kafka-migrate
          args:
            - "kafkachannels.messaging.knative.dev"
